name: Home Assistant compatibility
on:
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test-current-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - run: pip install -r requirements-dev.txt
      - run: python -m pytest tests/ --cov=custom_components.postnl --cov-fail-under=95 -v
